[package]
name = "cashier-server"
version = "0.1.0"
authors = ["Sun Ziping <sunziping2016@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.9.0"
actix-files = "0.2.2"
actix-multipart = "0.2"
actix-rt = "1.1"
actix-service = "1.0.5"
actix-web = "2.0"
actix-web-actors = "2.0"
actix-web-validator = "1.0.0"
base64 = "0.12.3"
bcrypt = "0.8.0"
cashier-query = { path = "../cashier-query" }
chrono = { version = "0.4", features = ["serde"] }
clap = "3.0.0-beta.1"
derive_more = "0.99.7"
env_logger = "0.7.1"
err-derive = "0.2.4"
futures = "0.3.5"
image = "0.23.5"
Inflector = "*"
jsonwebtoken = "7.1.1"
lazy_static = "1.4.0"
lettre = "0.10.0-alpha.1"
log = "0.4.8"
mime = "0.3"
multer = { path = "../multer" }
redis = "0.16.0"
regex = "1"
rand = "0.7.3"
rpassword = "4.0.5"
rustls= "0.17.0"
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0"
shell-macro = { path = "../shell-macro" }
strum = "0.18.0"
strum_macros = "0.18.0"
tokio = { version = "0.2.21", features = ["full"] }
tokio-postgres = { version = "0.5.4", features = ["with-chrono-0_4"] }
unzip-n = "0.1.1"
validator = "0.10"
validator_derive = "0.10"
webpki-roots = "0.20.0"
